// Generated by https://quicktype.io

using System;

namespace Joinrpg.Trelony.LegacyConsoleImporter.JsonDataModel
{
    using Newtonsoft.Json;

    public partial class GameDateJson
    {
        [JsonProperty("game_date_id")] public int GameDateId { get; set; }

        [JsonProperty("game_id")] public int GameId { get; set; }

        [JsonProperty("begin")] public DateTimeOffset? Begin { get; set; }

        [JsonProperty("time")] public int Time { get; set; }

        [JsonProperty("hidden_flag")]
        [JsonConverter(typeof(BoolConverter))]
        public bool HiddenFlag { get; set; }

        [JsonProperty("order")] public int Order { get; set; }
    }


}
