// Generated by https://quicktype.io

using Newtonsoft.Json;

namespace Joinrpg.Trelony.LegacyConsoleImporter.JsonDataModel
{
    public class PolygonJson
    {
        [JsonProperty("polygon_id")] public int PolygonId { get; set; }

        [JsonProperty("polygon_name")] public string PolygonName { get; set; }

        [JsonProperty("sub_region_id")] public int SubRegionId { get; set; }

        [JsonProperty("meta_polygon")]
        [JsonConverter(typeof(BoolConverter))]
        public bool MetaPolygon { get; set; }

        [JsonProperty("deleted_flag")]
        [JsonConverter(typeof(BoolConverter))]
        public bool DeletedFlag { get; set; }
    }
}